# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WebService-TagTheNet
version:      0.01
version_from: lib/WebService/TagTheNet.pm
installdirs:  site
requires:
    LWP::UserAgent:                0
    Test::Simple:                  0.44
    XML::XPath:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
